config/routes.rb
Rails.application.routes.draw do
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'
  
  devise_for :users
 # get 'storefront/all_items'
  #get 'storefront/items_by_category'
  #get 'storefront/items_by_brand'
    root 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category' 

  get 'branding' => 'storefront#items_by_brand'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/line_item.rb
# line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :order, optional: true
end

app/models/order.rb
# order.rb
class Order < ApplicationRecord
  has_many :line_items
  belongs_to :user, optional: true

  serialize :order_items, Hash
end

app/models/product.rb
# product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :categories, :brands

  def categories
  	@categories = Category.order(:name)
  end

def brands
  @brands = Product.pluck(:brand).sort.uniq
end
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add_to_cart
  line_item = LineItem.create(product_id: params[:product_id], quantity: params[:quantity])

  line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

  redirect_back(fallback_location: root_path)
   end

def view_order
    @line_items = LineItem.all
end

  def checkout
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
  @product = Product.new
  @categories = Category.all
end

def edit
  @categories = Category.all
end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
  params.require(:product).permit(:name, :price, :quantity, :description, :brand, 
    :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  def all_items
  	@products = Product.all
  end

  def items_by_category

  #to get to this page: catergorical_path(params[:category_id])

  @products = Product.where(category_id: params[:category_id])
  @category = Category.find(params[:category_id])

	end

    def items_by_brand
    @products = Product.where(brand: params[:brand])
    @brand = params[:brand]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h1>Cart#checkout</h1>
<p>Find me in app/views/cart/checkout.html.erb</p>

app/views/cart/view_order.html.erb
<h2>My Cart</h2>

<div>
  <% @line_items.each do |line_item| %>
    <li><%= line_item.product.name %></li>
    <li><%= number_to_currency line_item.product.price %></li>
    <li>Qty: <%= line_item.quantity %></li>
    <li>Subtotal: <%= number_to_currency line_item.line_item_total %></li>
  <% end %>
</div>

<div>
  <%= link_to "Proceed to Checkout?", checkout_path, class: "btn btn-success" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commerceproj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- within layouts/application.html.erb -->

<ul class="nav navbar-nav navbar-right">
  <li><%= link_to "View Cart", view_order_path %></li>

    <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% @categories.each do |category| %>
      <li><%= link_to category.name, categorical_path(category_id: category.id) %></li>
    <% end %>
  </ul>
</li>

<!-- Brands -->
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands<span class="caret"></span></a>
  <ul class="dropdown-menu">
    <% @brands.each do |brand| %>
      <li><%= link_to brand, branding_path(brand: brand) %></li>
    <% end %>
      <li><%= link_to 'All', root_path %></li>
  </ul>
</li> 
<!-- End Brands -->  


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
  <%= yield %>
</div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="form-group">
  <%= form.select :category_id, @categories.collect { |c| [ c.name, c.id ]}, {include_blank: "Please select a category" } %>
</div>

<div class="form-group">
  <strong>Upload Product Image: </strong>
  <%= form.file_field :image %>
</div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/_productloop.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="well">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url, size: "50" %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>
  <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
    <span class="glyphicon glyphicon-plus"></span> Quick Info
  </a>
</p>
      </div>
    </div>
    <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
      </div>
      <div class="modal-body">
        <% if product.image.url.nil? == false %>
          <p><%= image_tag product.image.url, size: "50", class: "storefront-pics" %></p>
        <% end %>
        <h3><%= link_to product.name, product %></h3>
        <p><%= number_to_currency product.price %></p>
        <p>made by <%= product.brand %></p>
      </div>
      <div class="modal-footer">
  <!-- Delete those "Save Changes" and "Close" buttons that were here -->
  <p>
  <%= form_tag add_to_cart_path do %>
    <%= hidden_field_tag :product_id, product.id %>
    <%= number_field_tag :quantity, nil, placeholder: "How many?" %>
    <%= submit_tag "Add to Cart", class: "btn btn-primary" %>
  <% end %>
  </p>
</div>
    </div>
  </div>
</div>
  <% end %>
</div>

app/views/storefront/all_items.html.erb
<!-- all_items.html.erb -->

<h1>Welcome to Tech Talent Store</h1>
<p>Give us your money!</p>

<%= render 'productloop' %>

app/views/storefront/items_by_brand.html.erb
<!-- items_by_brand.html.erb -->

<h1>All of Our <%= @brand %> Products</h1>

<%= render 'productloop' %>

app/views/storefront/items_by_category.html.erb
<!-- items_by_category.html.erb -->

<h1>Our Entire Stock of <%= @category.name %></h1>

<%= render 'productloop' %>